### ISSUE TITLE
windows support [tracking issue]

### ISSUE THREAD

**Issue by hendriknielaender** [hendriknielaender/zvm#10]
tbd

**Comment by ellacrity** [comment]
What needs to be done to assist with adding better Windows support? I switched my machines to using `zvm` for managing my Zig toolchain(s) recently on both developer machines. I used `scoop` to install `zvm` for Windows and everything went very smoothly. On Linux, I had the same experience (very simple to use and easy to set up).

If there is anything in particular you want added for better Windows support, I am more than happy to try and help.

Thanks for the amazing project!

**Comment by jinzhongjia** [comment]
Great project, I've forked the repo and I'll try to add windows support

**Comment by jinzhongjia** [comment]
I briefly took a look at the current implementation and to be honest, it's a bit weird.

Currently, symbolic links are used, and getenv is used to obtain home. These two problems are mainly due to these two problems. On Windows, symbolic links require administrator rights or `SeCreateSymbolicLinkPrivilege` right.

This means that simply using symbolic links is not user-friendly. Can we copy the file directly?

**Comment by jinzhongjia** [comment]
And I checked other zig version managers, and the results don’t look ideal.
And most of them lack Windows support. Indeed, the Windows API is very strange, and Zig’s support for Windows is not very good.

**Comment by hendriknielaender** [comment]
Hi @jinzhongjia,

Cool that you like the project! I'm thrilled to hear that you are working on adding Windows support. Contributions are greatly appreciated.

Regarding the use of symbolic links, I agree that the current implementation poses challenges, especially on Windows where symbolic links require special permissions. Given zig's limited support for symlinks on Windows, my first suggestion is to consider using some native C libraries until Zig's api got better. This approach worked well for us with the extraction (libarchive) function in versions 0.1 and 0.2 of zvm.
https://github.com/hendriknielaender/zvm/pull/24

Feel free to reach out if you need any assistance or have more ideas to discuss. I'm happy to help!

**Comment by jinzhongjia** [comment]
Native c library? Aha
Is there any C library that supports creating symbolic links without permissions?

**Comment by hendriknielaender** [comment]
No, not for symlinks 😅 I meant more the general approach. I think your idea of copy the file instead should work, something like this:

```zig
const symlink = try std.fs.path.join(allocator, &[_][]const u8{ dir, "master" });
defer allocator.free(symlink);
if (builtin.os.tag == .windows) {
  var file = try std.fs.createFileAbsolute(symlink, .{});
  defer file.close();
  try file.writer().writeAll(url.version);
}
```

**Comment by jinzhongjia** [comment]
I get it

**Comment by jinzhongjia** [comment]
Currently I'm stuck on decompressing the zip. I don't understand why zig's zip function is designed so strangely.

**Comment by jinzhongjia** [comment]
https://ziglang.org/documentation/master/std/#std.zip.decompress

**Comment by jinzhongjia** [comment]
It requires me to specify a decompress_size, strange behavior

**Comment by jinzhongjia** [comment]
Ok I found some related examples and I will try it
https://github.com/ziglang/zig/pull/19729
https://github.com/ziglang/zig/issues/17408

**Comment by jinzhongjia** [comment]
![image](https://github.com/hendriknielaender/zvm/assets/41784264/d1b1871e-46a3-4bae-97c9-2de3fcd26936)
There is currently no problem running the program, but the following paths need to be adjusted

**Comment by jinzhongjia** [comment]
In addition, I wonder if we can expose the various functions of the whole to the outside world as modules?
This will make it easier for others to integrate

**Comment by hendriknielaender** [comment]
> In addition, I wonder if we can expose the various functions of the whole to the outside world as modules? This will make it easier for others to integrate

Could you please provide more specific details on what you mean by "exposing the various functions of the whole to the outside world as modules"? To ensure we address this properly, it would be helpful if you could open an issue with the detailed requirements and use cases.

**Comment by jinzhongjia** [comment]
To put it simply, it just exposes the package to the outside world to facilitate third-party calls.

**Comment by hendriknielaender** [comment]
https://github.com/hendriknielaender/zvm/pull/42
