### ISSUE TITLE
Program conflicts

### ISSUE THREAD

**Issue by tristanisham** [hendriknielaender/zvm#16]
Hi,

I currently maintain and build ZVM https://github.com/tristanisham/zvm and we use the same directory path for programs and installations. 

I'm all for more Zig version managers, but would you consider changing the directory your version manager uses to not conflict with mine? If users ever switch it may result in both of our programs malfunctioning.

**Comment by hendriknielaender** [comment]
Hello @tristanisham,

Firstly, thank you for reaching out and making aware of the potential conflict. I appreciate the collaborative spirit! To ensure that users have a smooth experience when using both of our tools, I'll create a PR to adjust the directory path. Let's ensure compatibility and a great user experience for everyone! 👍
