### ISSUE TITLE
Segmentation fault when setting version

### ISSUE THREAD

**Issue by hendriknielaender** [hendriknielaender/zvm#37]
### Zig Version

0.13.0-dev.73+db890dbae

### Steps to Reproduce and Observed Behavior

Symlink is created without any issues. Zig version is set correctly. But the dump stack trace msg should not be shown.

[3/4] Setting Version [1/1] Segmentation fault at address 0x10a5ea000
Unable to dump stack trace: debug info stripped
[1]    22631 abort      zvm i master

### Expected Behavior

No seg fault

**Comment by dsus-ch** [comment]
Unfortunately, I also encountered this situation
![image](https://github.com/hendriknielaender/zvm/assets/110248561/ab1116de-53a1-49af-9142-a929309ece55)
@hendriknielaender

**Comment by hendriknielaender** [comment]
@dsus-ch issue should be resolved with this fix https://github.com/hendriknielaender/zvm/pull/45

Verified it with zvm version `0.4.2`, im closing this one. Happy to re-open if its still an issue for you
