### ISSUE TITLE
Use minisign to verify tarball

### ISSUE THREAD

**Issue by hendriknielaender** [hendriknielaender/zvm#43]
Use the official minisign to verify the downloaded zig version.

https://ziglang.org/download/

**Comment by jinzhongjia** [comment]
for verify tarball, we can use this lib, https://github.com/jedisct1/zig-minisign/tree/main

**Comment by hendriknielaender** [comment]
Since the RFCs specs are relatively small, I would prefer if we built it into zvm. We also only need the verification part.

**Comment by jinzhongjia** [comment]
Is there any specific implementation specification? I checked the upstream repository of minisign and found no specification.

**Comment by hendriknielaender** [comment]
It's the [EdDS-Algorithm](https://en.wikipedia.org/wiki/EdDSA) that they implemented in minisign.
https://ed25519.cr.yp.to/

[RFC8032](https://datatracker.ietf.org/doc/html/rfc8032)
