### ISSUE TITLE
idea: use syscall `exec` on linux or mac ?

### ISSUE THREAD

**Issue by jinzhongjia** [hendriknielaender/zvm#48]
What do you think about adding `exec` syscall for linux and mac, which allows users or linux distributions to directly softlink zvm, and maybe we can try to adjust zvm's config dir to compile-time settings?

**Comment by hendriknielaender** [comment]
Yeah that sounds great 👍

**Comment by jinzhongjia** [comment]
ok, I will try to implement it

**Comment by jinzhongjia** [comment]
What do you think about introducing external packages? I think the current command line parsing part is not complete. It would be better to introduce an external command line parsing package.

**Comment by jinzhongjia** [comment]
If it is completely implemented internally, it would be a waste to reinvent the wheel.

**Comment by hendriknielaender** [comment]
Why would we need an external package for that? Which feature do we need?

**Comment by jinzhongjia** [comment]
Some of the features implemented so far are indeed sufficient, but I think it is not  elegant.
